# -*- coding: utf-8 -*-

CODES = {

    # Informational.
    100: ('Continue',),
    101: ('Switching Protocols',),
    102: ('Processing',),
    103: ('Checkpoint',),
    122: ('Uri too long',),
    200: ('OK',),
    201: ('Created',),
    202: ('Accepted',),
    203: ('Non authoritative info',),
    204: ('No content',),
    205: ('Reset content',),
    206: ('Partial content',),
    207: ('Multi status',),
    208: ('Already reported',),
    226: ('Im used',),

    # Redirection.
    300: ('Multiple choices',),
    301: ('Moved permanently',),
    302: ('Found',),
    303: ('See other',),
    304: ('Not modified',),
    305: ('Use proxy',),
    306: ('Switch proxy',),
    307: ('Temporary redirect',),
    308: ('Permanent redirect',),

    # Client Error.
    400: ('Bad request',),
    401: ('Unauthorized',),
    402: ('Payment required',),
    403: ('Forbidden',),
    404: ('Not found',),
    405: ('Method not allowed',),
    406: ('Not acceptable',),
    407: ('Proxy authentication required',),
    408: ('Request timeout',),
    409: ('Conflict',),
    410: ('Gone',),
    411: ('Length required',),
    412: ('Precondition failed', 'precondition'),
    413: ('Request entity too large',),
    414: ('Request uri too large',),
    415: ('Unsupported media type',),
    416: ('Requested range not satisfiable',),
    417: ('Expectation failed',),
    418: ('Im a teapot', 'teapot',),
    422: ('Unprocessable entity',),
    423: ('Locked',),
    424: ('Failed dependency',),
    425: ('Unordered collection',),
    426: ('Upgrade required',),
    428: ('Precondition required',),
    429: ('Too many requests',),
    431: ('Header fields too large',),
    444: ('No response', 'none'),
    449: ('Retry with', 'retry'),
    450: ('Blocked by windows parental controls',),
    451: ('Unavailable for legal reasons',),
    499: ('Client closed request',),

    # Server Error.
    500: ('Internal server error',),
    501: ('Not implemented',),
    502: ('Bad gateway',),
    503: ('Service unavailable',),
    504: ('Gateway timeout',),
    505: ('Http version not supported',),
    506: ('Variant also negotiates',),
    507: ('Insufficient storage',),
    509: ('Bandwidth limit exceeded',),
    510: ('Not extended',),
}
